/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'customer' : Principal,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : ExternalBlob,
  'category' : string,
  'price' : bigint,
}
export interface Review {
  'customer' : Principal,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, string, bigint, bigint, ExternalBlob, string, boolean],
    undefined
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string, Principal], undefined>,
  'filterProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listOrdersByCustomer' : ActorMethod<[Principal], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listReviews' : ActorMethod<[string], Array<Review>>,
  'listUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'submitReview' : ActorMethod<[string, bigint, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, bigint, ExternalBlob, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];